plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '1.0.20'
}

group = 'com.tcto.rpg'
version = '0.1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

neoForge {
    version = project.neoforge_version
    runs {
        client {
            client()
        }
        server {
            server()
        }
        data {
            data()
        }
    }
}

dependencies {
    implementation "net.neoforged:neoforge:${project.neoforge_version}"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
