package com.tcto.rpg.docs;

import java.io.IOException;
import java.nio.file.Path;
import java.util.Map;

public class SchemaDocGenerator {
    private final MarkdownDocWriter writer = new MarkdownDocWriter();

    public void generate(Path outputRoot) throws IOException {
        Map<String, String> docs = Map.ofEntries(
            Map.entry("job_schema.md", "Job Schema"),
            Map.entry("skill_schema.md", "Skill Schema"),
            Map.entry("item_schema.md", "Item Schema"),
            Map.entry("monster_schema.md", "Monster Schema"),
            Map.entry("boss_schema.md", "Boss Schema"),
            Map.entry("dungeon_schema.md", "Dungeon Schema"),
            Map.entry("quest_schema.md", "Quest Schema"),
            Map.entry("shop_schema.md", "Shop Schema"),
            Map.entry("event_schema.md", "Event Schema"),
            Map.entry("content_pack_schema.md", "Content Pack Schema"),
            Map.entry("operator_commands.md", "Operator Commands")
        );
        for (Map.Entry<String, String> entry : docs.entrySet()) {
            writer.write(outputRoot.resolve(entry.getKey()), entry.getValue(), "Generated by /tctorpg docs generate.");
        }
    }
}
